

#ifndef TEST_CONFIG_H_
#define TEST_CONFIG_H_

#define TEST_CONFIG_ALL false
#define TEST_CONFIG_ALL_NONE false

#define TEST_CONFIG_TEST(TEST) (!TEST_CONFIG_ALL_NONE && (TEST || TEST_CONFGI_ALL))

/*
 *
 */
#define TEST_CONFIG_TEST_TEST TEST_CONFIG_TEST(true)
#define TEST_CONFIG_SVC_TEST TEST_CONFIG_TEST(true)

#define TEST_CONFIG_ASSEMBLER_TEST TEST_CONFIG_TEST(true)
#define TEST_CONFIG_READER_TEST TEST_CONFIG_TEST(true)

#endif
